### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by sctrueew** [sdcb/sdcb-openvino-yolov8-cls#1]
Hi @sdcb, thanks for your work. I get the wrong result when I use the code. I exported the model with this

yolo export model=best.pt format=openvino imgsz=224
![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/07fdbb22-c54e-48de-939f-3d9ca61a869a)

but the result is wrong. When I use this 

yolo predict model=best.pt imgsz=224 source=test 
yolo predict model=\openvino_model\ imgsz=224 source=test
![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/2f4668d0-b679-497a-a51e-ddc7792122bb)

the result is correct. 
Where is the problem?
Thank you!

**Comment by sdcb** [comment]
Sorry I didn't get your point, what's the different? what's your code?

**Comment by sctrueew** [comment]
@sdcb Hi,
I trained a model based on my own data. I used this command to test

yolo export model=best.pt format=openvino imgsz=224
yolo predict model=\openvino_model\ imgsz=224 source=test

, the output was correct and the accuracy of each test sample was almost equal to 1. 
this image:
![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/0ec4c868-4047-4a53-8806-e8ad7ff783cf)

I converted the model using the command below 
yolo export model=best.pt format=openvino imgsz=224

and used your code for inference, but the output was different. It detects errors and accuracy is another thing.

![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/d24611f6-c604-4222-84b8-134f3c171410)

This is the code I am using:

    `static void Main()
    {
    
        string modelFile = @"best_openvino_model\best.xml";
    
        using Model rawModel = OVCore.Shared.ReadModel(modelFile);
        using PrePostProcessor pp = rawModel.CreatePrePostProcessor();
        using (PreProcessInputInfo inputInfo = pp.Inputs.Primary)
        {
            inputInfo.TensorInfo.Layout = Layout.NHWC;
            inputInfo.ModelInfo.Layout = Layout.NCHW;
        }
        using Model m = pp.BuildModel();
        using CompiledModel cm = OVCore.Shared.CompileModel(m, "CPU");
        using InferRequest ir = cm.CreateInferRequest();
    
        Shape inputShape = m.Inputs.Primary.Shape;
        Stopwatch stopwatchTotal = new Stopwatch();
        stopwatchTotal.Start();
        var files = Directory.GetFiles(@"test");
        foreach (var item in files)
        {
            using Mat src = Cv2.ImRead(item);// @"hen.jpg");
            Stopwatch stopwatch = new();
            using Mat resized = src.Resize(new Size(inputShape[2], inputShape[1]));
            using Mat f32 = new();
            resized.ConvertTo(f32, MatType.CV_32FC3, 1.0 / 255);
    
            using (Tensor input = f32.AsTensor())
            {
                ir.Inputs.Primary = input;
            }
            double preprocessTime = stopwatch.Elapsed.TotalMilliseconds;
            stopwatch.Restart();
    
            ir.Run();
            double inferTime = stopwatch.Elapsed.TotalMilliseconds;
            stopwatch.Restart();
    
            using (Tensor output = ir.Outputs.Primary)
            {
                ReadOnlySpan<float> data = output.GetData<float>();
                int maxIndex = MaxIndexOfSpan(data);
                double postProcessTime = stopwatch.Elapsed.TotalMilliseconds;
                stopwatch.Stop();
    
                Console.WriteLine($"{item} class id={maxIndex}, score={data[maxIndex]:F2}");
            }
        }
        stopwatchTotal.Stop();
        Console.WriteLine($"Total time: {stopwatchTotal.Elapsed.TotalMilliseconds:F2}ms");
    }`

**Comment by sdcb** [comment]
Hmm don't know but would it possible that we should reverse RGB in this case?

**Comment by sctrueew** [comment]
Is it possible to share my model with you to check it? I checked different ways but didn't understand anything.

**Comment by sctrueew** [comment]
@sdcb, I need your help to fix it.

 using Mat src1 = Cv2.ImRead(item);
 using Mat src = src1.CvtColor(ColorConversionCodes.RGB2BGR);

I reversed to BGR but the result didn't change.

**Comment by sdcb** [comment]
Ok, so it's not about RGB swap, I think I did a resize when provided input was not a square, can you check that is our code using:
* stretch resize, or 
* padding resize?

I think this is also important when proprocessing.

**Comment by sctrueew** [comment]
I checked it, it's stretch resize.

![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/0a3cf62e-d399-4d4f-90de-4c051b135b0b)

**Comment by sdcb** [comment]
can you try change into padding resize, resize longer edge into specific model size first, then using CopyMakeBolder method to padding the shorter edge.

**Comment by sctrueew** [comment]
I changed the resizing method with 

![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/07d6b57e-69ba-4e3a-9133-2c92dba1fad4)

`
   static Mat ResizeWithCopyMakeBorder(Mat image, int newWidth, int newHeight)
    {
        double aspectRatio = (double)image.Width / image.Height;

        // Calculate the new dimensions based on the original aspect ratio
        int calculatedWidth = (int)(newHeight * aspectRatio);
        int calculatedHeight = (int)(newWidth / aspectRatio);

        int finalWidth, finalHeight;

        // Choose the dimensions that fit within the specified size
        if (calculatedWidth <= newWidth)
        {
            finalWidth = calculatedWidth;
            finalHeight = newHeight;
        }
        else
        {
            finalWidth = newWidth;
            finalHeight = calculatedHeight;
        }

        // Resize the image
        Mat resizedImage = new Mat();
        Cv2.Resize(image, resizedImage, new Size(finalWidth, finalHeight));

        // Calculate the borders to add
        int top = (newHeight - finalHeight) / 2;
        int bottom = newHeight - finalHeight - top;
        int left = (newWidth - finalWidth) / 2;
        int right = newWidth - finalWidth - left;

        // Create a canvas with borders
        Mat canvas = new Mat();
        Cv2.CopyMakeBorder(resizedImage, canvas, top, bottom, left, right, BorderTypes.Constant, Scalar.All(0));

        return canvas;
    }
`


  Mat resized = ResizeWithCopyMakeBorder(src, inputShape[2], inputShape[1]);

but the result is always class id 2 that should be class id 3

![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/fdbfb94b-99f0-4851-85cf-2487ce603e21)

**Comment by sdcb** [comment]
Hmm, interesting, would it possible that class id is actually 3 but it's 0 based lol?

**Comment by sctrueew** [comment]
It's strange for me too. I don't know what to do exactly

**Comment by sdcb** [comment]
at least it seems the result seems more stable lol, would it possible that you should CopyMakeBolder with the border pixel color instead of just black?

**Comment by sctrueew** [comment]
Can you give me an example?

**Comment by sdcb** [comment]
Sure, you can use the `copyMakeBorder` function with the `BORDER_REPLICATE` option, that replicates the border pixel values. Here's a quick modification to your function:

```c#
static Mat ResizeWithCopyMakeBorder(Mat image, int newWidth, int newHeight)
{
    double aspectRatio = (double)image.Width / image.Height;

    // Calculate the new dimensions based on the original aspect ratio
    int calculatedWidth = (int)(newHeight * aspectRatio);
    int calculatedHeight = (int)(newWidth / aspectRatio);

    int finalWidth, finalHeight;

    // Choose the dimensions that fit within the specified size
    if (calculatedWidth <= newWidth)
    {
        finalWidth = calculatedWidth;
        finalHeight = newHeight;
    }
    else
    {
        finalWidth = newWidth;
        finalHeight = calculatedHeight;
    }

    // Resize the image
    Mat resizedImage = new Mat();
    Cv2.Resize(image, resizedImage, new Size(finalWidth, finalHeight));

    // Calculate the borders to add
    int top = (newHeight - finalHeight) / 2;
    int bottom = newHeight - finalHeight - top;
    int left = (newWidth - finalWidth) / 2;
    int right = newWidth - finalWidth - left;

    // Create canvas and add borders with BORDER_REPLICATE method
    Mat canvas = new Mat();
    Cv2.CopyMakeBorder(resizedImage, canvas, top, bottom, left, right, BorderTypes.Replicate);

    return canvas;
}
```

In this modification, when the `CopyMakeBorder` function is called, it uses `BorderTypes.Replicate`, which replicates the edge pixels rather than adding a constant value border. This could potentially help with the issue you're encountering with classes due to image resizing.

**Comment by sctrueew** [comment]
I tested it again with that method but the result was not correct:

![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/11d83d55-849c-4032-8440-757e1637d035)

![image](https://github.com/sdcb/sdcb-openvino-yolov8-cls/assets/5433346/c0deadd4-6d4b-44a8-b47e-eb1bfb197621)

**Comment by sctrueew** [comment]
Would it be possible for you to give me your email address so I can send the model and data for review?

**Comment by sctrueew** [comment]
I couldn't solve the problem. I need your tips to fix it.

**Comment by sctrueew** [comment]
@sdcb Hi,
I solved the problem. thank you for helping

**Comment by sdcb** [comment]
Good to know, can you tell me how did you solved the problem?

**Comment by sctrueew** [comment]
Yes, initially, I resized the image to the network dimensions, ensuring that the aspect ratio was preserved and then I performed a centered crop to extract the region of interest. Finally, a Color Conversion step was applied to transform the image from the RGB to the BGR color space.

Here is my method:
 using Mat resized = ResizeAndCropCenter(src, netSize);

  ```csharp
    private static Mat ResizeAndCropCenter(Mat inputImage, Size targetSize)
    {
        // Calculate the resize factor to maintain aspect ratio
        float resizeFactor = Math.Max(targetSize.Width / (float)inputImage.Cols, targetSize.Height / (float)inputImage.Rows);

        // Resize the image
        using Mat resizedImage = new Mat();
        Cv2.Resize(inputImage, resizedImage, Size.Zero, resizeFactor, resizeFactor, InterpolationFlags.Linear);

        // Calculate the crop region in the center
        int x = (int)(0.5 * (resizedImage.Cols - targetSize.Width));
        int y = (int)(0.5 * (resizedImage.Rows - targetSize.Height));

        // Crop the center region
        Rect cropRegion = new Rect(new Point(x, y), targetSize);
        Mat croppedImage = new Mat(resizedImage, cropRegion);

        Cv2.CvtColor(croppedImage, croppedImage, ColorConversionCodes.RGB2BGR);
        return croppedImage;
    }
